### ISSUE TITLE
incorrect bind variables substitution

### ISSUE THREAD

**Issue by Ypiskare** [laurenz/pgreplay#10]
Hi Luarenz,

The next example seems as incorrect bind variable substitution.
For example:

On the 1-st server, PG had logged:

_execute <unnamed>: WITH main_query AS (select row_number() over () rn, dc.* from (SELECT  * FROM(
SELECT ID, concatwithdelimiter(code_statistic,statistic_short) as TEXT FROM report_statistic
) tbl WHERE 1=1
  AND  ( ( ( (ID = $1) ) ) )  ORDER BY TEXT asc) dc) SELECT main_query.* FROM main_query  WHERE rn > $2 AND rn <= $3 + $4"	parameters: $1 = '26', $2 = '0', $3 = '0', $4 = '29'_

On the 2-nd server  whith pgreplay, PG had logged the error:

_operator is not unique: unknown + unknown		
Could not choose a best candidate operator. You might need to add explicit type casts.				WITH main_query AS (select row_number() over () rn, dc.* from (SELECT  * FROM(
SELECT ID, concatwithdelimiter(code_statistic,statistic_short) as TEXT FROM report_statistic
) tbl WHERE 1=1
  AND  ( ( ( (ID = $1) ) ) )  ORDER BY TEXT asc) dc) SELECT main_query.* FROM main_query  WHERE rn > $2 AND rn <= $3 + $4_

Is there some way how to avoid such errors when replay with pgreplay? 

Regards,
Yury

**Comment by laurenz** [comment]
This is a shortcoming of pgreplay I hadn't been aware of.

Unfortunately there is nothing I can do about it.

In a query like this, the client would send data type information in the BIND message so that there is no ambiguity (otherwise you'd get just the same error).
But this information is not logged, and so pgreplay cannot replay it.

Unless you don't have a lot of these statements, it shouldn't be a big problem; all that happens is that you will have a slightly higher error count than in the original run.

I have added documentation about this to the README file.

**Comment by Ypiskare** [comment]
Hi Luarenz,

I found a workaround for the issue.
Everything will work correctly if I replace in my example of the logged statement **$1 + $2** with **$1::nemeric + $2**.

So, more general replacment is:

sed -i 's/\(\$[0-9]\+\)\( *[^,] *\$\)/\1::numeric\2/g' postgres_log_file.csv

Regards,
Yury

**Comment by Ypiskare** [comment]
> Hi Luarenz,
> 
> I found a workaround for the issue.
> Everything will work correctly if I replace in my example of the logged statement **$1 + $2** with **$1::nemeric + $2**.
> 
> So, more general replacment is:
> 
> sed -i 's/($[0-9]+)( *[^,] *$)/\1::numeric\2/g' postgres_log_file.csv
> 
> Regards,
> Yury

**Comment by laurenz** [comment]
Yes, certainly &ndash; if you write the query in a way that it does not require the data type information, it will replay without an error.

That `sed` command will certainly solve the problem if you have no other statements of the form `$1 + $2` in your log. `$1` could be a `date` value...

Do you want to keep this issue open for a certain reason?

**Comment by Ypiskare** [comment]
Ah! You are right! I forgot about date type. But I'm sure  I can write more complex handler of postgres log  if needed. 

Many thanks for answers. You may close the issue.

Regards,
Yury
