### ISSUE TITLE
Compiler warnings on MacOS

### ISSUE THREAD

**Issue by deeprave** [laurenz/pgreplay#11]
The readme requested feedback when building for platforms not specifically tested.

OSX Mojave 10.14
Postgresql 11.1
Xcode 10.1

$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**pgreplay successfully compiles and appears to work**, but with warnings. See attachment for the build log. Most errors seem to be related to session_id and format string mismatch.

[pgreplay-build.txt](https://github.com/laurenz/pgreplay/files/2704653/pgreplay-build.txt)

**Comment by laurenz** [comment]
Thanks for the report!
I'll get back to it after my vacations.

**Comment by laurenz** [comment]
Could you try with [my latest patch](https://github.com/laurenz/pgreplay/archive/c9e93eab76f30409813abee46668ee7eca6116c9.zip) and see if that fixes the problem?
I don't have access to Mac OS.
