### ISSUE TITLE
make install fails on Mac OS X

### ISSUE THREAD

**Issue by jeffdoering** [laurenz/pgreplay#13]
configure.in is using AC_PROG_INSTALL and install-sh is bundled for systems without the BSD compatible install autoconf is looking for.

However; Makefile.in uses "-D" in a way that is not supported by the BSD install on my Mac OS X 10.14.4  system or the bundled install-sh script. I forced that by setting passing INSTALL=./install-sh to configure); make install still fails.

Mac OS 10.14.4 install options reported on 
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

The bundled install-sh reports:

./install-sh --help
Usage: ./install-sh [OPTION]... [-T] SRCFILE DSTFILE
   or: ./install-sh [OPTION]... SRCFILES... DIRECTORY
   or: ./install-sh [OPTION]... -t DIRECTORY SRCFILES...
   or: ./install-sh [OPTION]... -d DIRECTORIES...

In the 1st form, copy SRCFILE to DSTFILE.
In the 2nd and 3rd, copy all SRCFILES to DIRECTORY.
In the 4th, create DIRECTORIES.

Options:
     --help     display this help and exit.
     --version  display version info and exit.

  -c            (ignored)
  -C            install only if different (preserve the last data modification time)
  -d            create directories instead of installing files.
  -g GROUP      chgrp installed files to GROUP.
  -m MODE       chmod installed files to MODE.
  -o USER       chown installed files to USER.
  -s            strip installed files.
  -t DIRECTORY  install into DIRECTORY.
  -T            report an error if DSTFILE is a directory.

Environment variables override the default commands:
  CHGRPPROG CHMODPROG CHOWNPROG CMPPROG CPPROG MKDIRPROG MVPROG
  RMPROG STRIPPROG

This is clearly a minor issue I can work around; but ideally Makefile.in would still to autoconf supported install options so that worst-case the provided install-sh works and better-case any BSD compatible install would work (probably use a separate mkdir step to avoid depending on incompatible install behavior).

**Comment by laurenz** [comment]
Thanks for the report!

Could you check that [the latest development version](https://github.com/laurenz/pgreplay/archive/master.zip) with commit 1532119d09d85819a65e0bc7864bc5277b2d3946 fixes the problem?

**Comment by jeffdoering** [comment]
make install_bin and install_html look good. But install_man fails:

make install_man
/usr/bin/install -c -d pgreplay.1 /usr/local/share/man/man1
install: pgreplay.1 exists but is not a directory
make: *** [install_man] Error 71

Looks like "$<" was inadvertently left after the "-d" argument.

**Comment by laurenz** [comment]
Thanks for checking, and sorry for the sloppiness.

**Comment by jeffdoering** [comment]
Appreciate the quick turn around!

**Comment by laurenz** [comment]
You are welcome.
It is easy to provide a fix if you get a good problem report.
