### ISSUE TITLE
Unable to compile pgreplay on ubuntu 18.04

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [laurenz/pgreplay#14]
I am using commit 715e3330cf0f2af1a5f479b3f293c1904612b284

When configuring I get the following error:

```
$ ./configure
checking build system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking for fcntl.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for libpq-fe.h... no
configure: error: PostgreSQL header files not found
```

I do have the header file:

```
$ ls /usr/include/postgresql/libpq-fe.h
/usr/include/postgresql/libpq-fe.h
```

after running `export C_INCLUDE_PATH=/usr/include/postgresql` configure works.

Seems like ubuntu is doing this in their package building script as well:
See http://archive.ubuntu.com/ubuntu/pool/universe/p/pgreplay/pgreplay_1.2.0-2ubuntu2.diff.gz under https://packages.ubuntu.com/bionic/pgreplay

**Comment by laurenz** [comment]
You'll have to specify the location of your `pg_config` with

    ./configure --with-postgres=/software/postgres/bin

(Substitute the directory containing of `pg_config` for `/software/postgres/bin`.)

It's kind of a bug that `pc_config` is only called if explicitly specified that way, but I cannot get motivated to work on that right now.

**Comment by thomasdziedzic-pd** [comment]
That did indeed work:

```
$ which pg_config
/usr/bin/pg_config
```

```
./configure --with-postgres=/usr/bin
```

configure now succeeds.
