### ISSUE TITLE
pgreplay not working with RDS csvlog

### ISSUE THREAD

**Issue by zugolosian** [laurenz/pgreplay#17]
Hi, I was wondering what format pgreplay expects the CSV file to be generated in as I have a very large log file with lots of statements in it but it seems to skip all of them.

I put debug level up to 3 and I can see the lines are getting skipped but can't really see a reason why. 

Here's a sample log line that I would have expected to be parsed as a statement but wasn't, I'm happy to run through the log and re-order or modify values to make it work.
`2019-10-09 08:08:17.895 UTC,"obscured_username","obscured_database",24948,"172.31.39.150:52114",5d9d80de.6174,1,"SELECT",2019-10-09 06:40:30 UTC,3/221898308,0,LOG,00000,"duration: 0.033 ms  execute <unnamed>: SELECT ""public"".""users"".""families_id"" FROM ""public"".""users"" INNER JOIN ""public"".""relations"" ON ""public"".""relations"".""user_id"" = ""public"".""users"".""id"" WHERE ""public"".""relations"".""child_id"" = $1 AND ""public"".""relations"".""admin"" = $2 /*application:Application_name,controller_with_namespace:Api::V3::ActivityController,action:show*/","parameters: $1 = '123', $2 = 't'",,,,,,,,"Passenger AppPreloader: /myapp (forking...)"`

Here's some of the output from debug at the end:

```
Entering parse_csvlog_entry
Entering read_log_line, current line number 23152306
Encountered EOF
Leaving read_log_line
Leaving parse_errlog_entry
End-of-file encountered, creating disconnect item for session 0x6745718026424814585
Entering replay_create_disconnect
Leaving replay_create_disconnect
Entering remove_connection for session 0x6745718026424814585
Entering remove_all_pstmts
Leaving remove_all_pstmts
Leaving remove_connection
---------------------------
Item: time       = 623925914.117000
      session id = 0x6745718026424814585
      type       = disconnect
---------------------------
Leaving parse_provider
Entering file_consumer
Entering replay_free
Leaving replay_free
Leaving file_consumer
Entering parse_provider
Entering parse_csvlog_entry
Entering read_log_line, current line number 23152306
Encountered EOF
Leaving read_log_line
Leaving parse_errlog_entry
End-of-file encountered, signal end
Leaving parse_provider
Entering parse_provider_finish

Parse statistics
================

Log lines read: 23152305
Total SQL statements processed: 0
Simple SQL statements processed: 0
Parametrized SQL statements processed: 0
Named prepared SQL statements executions processed: 0
Cancel requests processed: 0
Fast-path function calls ignored: 0
Duration of recorded workload: 36 minutes 53.544 seconds
Leaving parse_provider_finish
Entering file_consumer_finish
Leaving file_consumer_finish
```

**Comment by laurenz** [comment]
That line cannot be parsed because you used `log_min_duration_statement` to log the statements.

As the documentation says, you have to use `log_statement = 'all'`.

One reason for that is that pgreplay needs to replay the statements at the time they start, not at the rime they finish.

**Comment by zugolosian** [comment]
Thanks for the speedy response. I'll try again. I misunderstood what you wrote here : https://github.com/laurenz/pgreplay/issues/7 to mean that I should use min duration
