### ISSUE TITLE
unknown type 58 encountered

### ISSUE THREAD

**Issue by gamename** [laurenz/pgreplay#2]
Hi,

I'm getting this error when I try to replay a file:

bash-4.2$ pgreplay -r /vagrant/postgresql-2015-01-15_211158.csv
Error: unknown type 58 encountered

This is a CentOS 7.0 box, with PostgreSQL 9.3

bash-4.2$ uname -a
Linux local-test-catalog-db-01 3.10.0-123.13.2.el7.x86_64 #1 SMP Thu Dec 18 14:09:13 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2$ psql --version
psql (PostgreSQL) 9.3.5

Thanks
-T

**Comment by laurenz** [comment]
Use the option `-r` only if you replay a "replay file" that has been generated with `pgreplay -f`.

To parse and replay a CSV file, omit `-r` and use `-c`.

**Comment by gamename** [comment]
Thanks! That worked.
