### ISSUE TITLE
replay and uuids

### ISSUE THREAD

**Issue by erichanson** [laurenz/pgreplay#20]
Question:  Any suggestions for dealing with UUIDs when doing a replay?  The problem is that during a replay, an insert will generate a different UUID for say a primary key then when it ran in production.  So then any queries that would use the UUID that was generated in production now doesn't work.  Anything that can be done about this?

**Comment by laurenz** [comment]
Hm, yes, that is a problem, and I don't think there is a solution to it.

pgreplay can only repeat what is in the log.
