### ISSUE TITLE
Will the program support pg11 onward?

### ISSUE THREAD

**Issue by MPaularBear** [laurenz/pgreplay#21]
when i do pgreplay, it just won't parse ,with error: paring line 1: log message does not begin with a log type.
i have no idea which format is acceptable, beyond setting log_line_prefix like in the instructions. thx

**Comment by laurenz** [comment]
Can you show a few lines from your log file? What `log_line_prefix` did you use?
PostgreSQL v11 should work.

**Comment by laurenz** [comment]
By the way, I will be on vacation for the next three weeks. So sorry in advance for the delay.

**Comment by laurenz** [comment]
Can you share the required information?
