### ISSUE TITLE
Transaction Deadlocks on Replay

### ISSUE THREAD

**Issue by TimGustafson** [laurenz/pgreplay#22]
I've been using pgreplay to test some theories out, but whenever I use it with a high-concurrency workload, I immediately hit transaction deadlocks because the transactions are being started/ended slightly out-of-sync with respect to the original server.  Is it possible to somehow increase the resolution with which transactions are started and stopped?  When using the CSV file format, is it possible to use the transaction ID to only start a transaction in the same order that it originally was started?

**Comment by laurenz** [comment]
This is the same problem as #12.

As mentioned there, pgreplay can only replay the statements in the order they appear in the log, but it cannot guarantee that they will be processed in that order.

In addition to the workarounds shown there, you could also set `lock_timeout` to a low value during replay. That will prevent hanging indefinitely long, but it will cause delays, and some statements won't be executed. Still, it might be good enough, if the deadlocks happen only rarely.

**Comment by TimGustafson** [comment]
Unfortunately, the deadlocks are very common with this workload, and we're talking about several thousand transactions per second.  Would another possibility be to ignore transactions when replaying the transactions, which would lead to data integrity issues on the target database (as would the `lock_timeout` option) but in this workload rollbacks are practically non-existent, so it would be a much better test.

**Comment by laurenz** [comment]
I see.
There is no option to exclude certain commands, but you could `grep` all `BEGIN` and `COMMIT` statements from the log file before replaying it.
I was under the impression that you are not talking about database deadlocks (which are automatically resolved after a second), but about hangs during replay that are never resolved. Which one is it?
Doing away with transactions would only reduce (not totally avoid!) the first kind of deadlocks, but not ones in pgreplay.

**Comment by TimGustafson** [comment]
Good point; excluding those via grep should work.

I am talking about database deadlocks.  They do not appear to be resolved after a second.  If I don't kill the query in PostgreSQL, it hangs indefinitely.  From what I can tell, the locks are caused by update queries that contain select clauses in them.  I'll give the grep suggestion a try and let you know what I find.

**Comment by laurenz** [comment]
That's not database deadlocks then.
They are live locks in the database, but the session that is not hanging is waiting (in pgreplay) for the hanging statement to complete.
Perhaps removing transactions will help, but it is not certain.

**Comment by laurenz** [comment]
Did it help?

**Comment by TimGustafson** [comment]
It's on my list for next week; sorry for the delay.
