### ISSUE TITLE
Invalid free on replaying server-side prepare "ROLLBACK; DEALLOCATE ALL".

### ISSUE THREAD

**Issue by lmwnshn** [laurenz/pgreplay#23]
Hi, thanks for writing pgreplay! pgreplay currently tries to free an invalid pointer and crashes when the replay contains a "ROLLBACK; DEALLOCATE ALL". This can happen when the `prepareThreshold` of a [server prepared statement](https://jdbc.postgresql.org/documentation/head/server-prepare.html) is crossed and then a rollback occurs; for example, the [psycopg3](https://www.psycopg.org/psycopg3/) PostgreSQL adapter will attempt to [DEALLOCATE ALL](https://github.com/psycopg/psycopg/blob/df0da90866f56db892d6957616f7297a387f6df3/psycopg/psycopg/_preparing.py#L184) as part of the rollback.

Environment:

- PostgreSQL 14, Ubuntu 20.04.
- Python3.8 with `psycopg` (aka psycopg3).

Stack trace:

```
(gdb) bt
#0  0x00007f0bc22c303b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f0bc22a2859 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f0bc230d29e in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f0bc231532c in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f0bc2316b5c in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#5  0x000055c591c2f8d0 in remove_all_pstmts (conn=<optimized out>) at parse.c:801
#6  0x000055c591c2f9c2 in remove_connection (session_id=7091101072822916911) at parse.c:1097
#7  0x000055c591c326ca in parse_provider () at parse.c:1476
#8  0x000055c591c2effc in main (argc=<optimized out>, argv=<optimized out>) at main.c:395
```

To reproduce, please find attached:

- [pgreplay_poc.py.txt](https://github.com/laurenz/pgreplay/files/8568224/pgreplay_poc.py.txt): Python script to generate minimal test case.
- [pgreplay_poc_logs.csv](https://github.com/laurenz/pgreplay/files/8568227/pgreplay_poc_logs.csv): The logs that demonstrate the segfault when replayed on a new database.
- [pgreplay_poc.sh.txt](https://github.com/laurenz/pgreplay/files/8568225/pgreplay_poc.sh.txt): boilerplate around cloning latest pgreplay, creating user/db, setting system options, running the Python script, getting the above logs, running pgreplay. **Will delete default `/var/lib/postgresql/14/main/log/` logs if run.** Assumes `/usr/bin/pg_config` exists. To use it, enter `pgreplay_pass` as password when prompted.

**Comment by laurenz** [comment]
Thanks for the detailed report, I'll have a look at it as soon as I find time.

**Comment by laurenz** [comment]
I think I found the bug. Could you try with the latest commits?

**Comment by lmwnshn** [comment]
I missed this notification, sorry. I just tested it, yes, it works now. Thanks! :)

**Comment by laurenz** [comment]
Thanks for the feedback.
