### ISSUE TITLE
Upgrade from pg 12 to pg 14

### ISSUE THREAD

**Issue by VasileiosGi** [laurenz/pgreplay#29]
I have a postgres db version 12.11. I replayed logs of 1 hour successfully. Transactions per second are about 10.000-15.000
When I upgraded database to 14.4 (and after I performed analyze) and replayed the same logs this changed drastically and transactions per second were about 1.000. Could you assist with this?

**Comment by laurenz** [comment]
Sorry, no. I feel responsible for keeping pgreplay in shape, but not for tuning your statements.
Use `pg_stat_statements` to figure out what is slow!

**Comment by VasileiosGi** [comment]
I replayed the same logs in the same dbs (with the same data I mean) but the second db was upgraded to 14 version.
Anyway thanks, it's a great tool!
