### ISSUE TITLE
./configure fails on pg15.0

### ISSUE THREAD

**Issue by TsinghuaLucky912** [laurenz/pgreplay#30]
1. centos7
2. pg15.0

![image](https://user-images.githubusercontent.com/49380232/229053778-b1767438-04df-474c-afd0-de735117f376.png)

**Comment by TsinghuaLucky912** [comment]
Sorry, I have seen the instructions

**Comment by laurenz** [comment]
Thanks for figuring it out by yourself.
You were probably missing the correct `--with-postgres` option to `configure`.
