### ISSUE TITLE
Opened connections

### ISSUE THREAD

**Issue by madtrick** [laurenz/pgreplay#31]
In a recent test run with pgreplay, the tool exited after it exhausted all the available connections to the database. See the images below for more details:

Execution of pgreplay
![image](https://github.com/laurenz/pgreplay/assets/48772/c8b94537-caa6-40ee-8c6a-327a6647f4e2)

Connection count 
![image](https://github.com/laurenz/pgreplay/assets/48772/4c813608-3a64-40d7-affd-1c252b28ba49)

Is this expected behaviour?

**Comment by laurenz** [comment]
Yes, that is expected, but only if you didn't set `log_disconnections` when you recorded the workload (then pgreplay won't know when a session ends).

**Comment by madtrick** [comment]
Ops, that's something I missed. Thanks for the hint.
