### ISSUE TITLE
AWS RDS support

### ISSUE THREAD

**Issue by gilly3** [laurenz/pgreplay#7]
Amazon's cloud database product, RDS, does not allow changing `log_line_prefix`.  See [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/AuroraPostgreSQL.Reference.html) and [forum post](https://forums.aws.amazon.com/thread.jspa?threadID=143460).  So we are stuck with `%t:%r:%u@%d:[%p]:`.  It would be great if pgreplay could be made to work with logs coming from AWS RDS.  pgbadger allows specifying the `log_line_prefix`.  Perhaps pgreplay could do something similar.

**Comment by laurenz** [comment]
I need `%c` in `log_line_prefix` so that I can identify sessions.

Is it an option to use `log_destination = csvlog`? That would be better anyway, and the documentation seems to suggest that `log_destination` is modifiable.

**Comment by gilly3** [comment]
Session id comes from process id and process start time.  [Documentation](https://www.postgresql.org/docs/9.5/static/runtime-config-logging.html#GUC-LOG-LINE-PREFIX):

> The %c escape prints a quasi-unique session identifier, consisting of two 4-byte hexadecimal numbers (without leading zeros) separated by a dot. The numbers are the process start time and the process ID

Could process id (`%p`) be made to substitute for session id?

I'll try `log_destination = csvlog` for future logs.  In the meantime, I'm stuck with a pile of logs from just before a failure that are in the wrong format.  I'd love to be able to replay _those_ logs and see if I can reproduce the failure.
