### ISSUE TITLE
Unable to parse the file

### ISSUE THREAD

**Issue by MayankDelhivery** [laurenz/pgreplay#8]
I am continuously getting the error as Error parsing line 1: no "|" found - log_line_prefix may be wrong

Does the code "|" expects to be present in log file?

**Comment by laurenz** [comment]
It looks like you didn't read this part of the documentation:

> First, you will need to record your real-life workload.
> For that, set the following parameters in postgresql.conf:
>
> [...]
> log_line_prefix = '%m|%u|%d|%c|'  (if you don't use CSV logging)

using `log_destination = 'csvlog'` makes things simpler.
