### ISSUE TITLE
Non-strict mode

### ISSUE THREAD

**Issue by NikolayS** [laurenz/pgreplay#9]
In some cases, we have problems with some lines of logs, and want to just exclude such log lines from consideration. Right now it's impossible -- pgreplay will print an error and stop parsing.

 It would be great to have an option to parse log file in "non-strict" mode – a mode, when incorrect log lines (those that have some parsing issues, like unmatched quotes), lead to having Warning instead of hard Error, so parsing continues. It would also be good to see how many Warnings were collected during parsing (how many lines we've "lost").

**Comment by laurenz** [comment]
I am not certain if that is a good idea.
Unless the log file is broken (e.g., you used a bad `log_line_prefix`), this should not happen.
Where did you encounter that problem? How can I reproduce these matched quotes?

Anyway, The change would have to be in `parse.c`, function `parse_provider`, around line 1439.
You'd have to catch the return code -1 and set the status to 0 if you want to ignore the condition.

Can you come up with a patch?
